-- 회원(MEMBER) 테이블
CREATE TABLE MEMBER (
    MEMBER_NO NUMBER PRIMARY KEY, -- 회원번호
    MEMBER_ID VARCHAR2(20) UNIQUE NOT NULL, -- 회원 아이디
    MEMBER_PWD VARCHAR2(20) NOT NULL, -- 회원 비밀번호
    MEMBER_NICK VARCHAR2(20) UNIQUE NOT NULL, -- 회원 닉네임
    MEMBER_NAME VARCHAR2(20) NOT NULL, -- 회원 이름
    MEMBER_BIRTHDAY DATE NOT NULL, -- 회원 생년월일
    MEMBER_GENDER CHAR(1), -- 회원 성별
    MEMBER_PHONE VARCHAR2(15) NOT NULL, -- 회원 전화번호
    MEMBER_SPHONE VARCHAR2(20) NOT NULL, -- 회원 안심번호
    MEMBER_EMAIL VARCHAR2(50), -- 회원 이메일
    MEMBER_ADDR VARCHAR2(200) NOT NULL, -- 회원 주소
    MEMBER_SIGNUP_DATE DATE DEFAULT SYSDATE, -- 회원 가입일
    MEMBER_AUTHORITY NUMBER DEFAULT 1 -- 회원 권한
);

ALTER TABLE VIDEO ADD CONSTRAINT VIDEO_CATEGORY_CODE_FK FOREIGN KEY(CATEGORY_CODE) REFERENCES CATEGORY;
ALTER TABLE AUCTION_BOARD ADD CONSTRAINT AUCTION_BOARD_CODE_FK FOREIGN KEY(CATEGORY_CODE) REFERENCES MAIN_CATEGORY;

-- AUCTION_BOARD 경매 게시판 테이블
CREATE TABLE AUCTION_BOARD (
    AUCTION_NO NUMBER PRIMARY KEY, -- 경매 번호
    AUCTION_TITLE VARCHAR2(20) NOT NULL, -- 경매 제목
    AUCTION_IMG VARCHAR2(500) NOT NULL, -- 경매 이미지
    AUCTION_DATE DATE DEFAULT SYSDATE, -- 경매 등록일
    ITEM_NAME VARCHAR2(100), -- 상품 이름
    ITEM_DESC VARCHAR2(2000), -- 상품 설명
    CURRENT_PRICE NUMBER(12), -- 현재 가격 (정밀도 수정)
    AUCTON_SMONEY NUMBER(12) NOT NULL,-- 경매 시작가
    AUCTION_EMONEY NUMBER(12) NOT NULL, -- 경매 최소 입찰가 (정밀도 수정)
    AUCTION_GMONEY NUMBER(12) NOT NULL, -- 경매 즉시 구매가 (정밀도 수정)
    AUCTION_NOWBUY_Y_N CHAR(1) DEFAULT 'N' CHECK (AUCTION_NOWBUY_Y_N IN ('Y', 'N')), -- 경매 즉시 구매 여부
    AUCTION_END_DATE DATE DEFAULT (SYSDATE + 30), -- 경매 마감일
    MEMBER_NO NUMBER NOT NULL, -- 회원 번호 (외래키)
    CATEGORY_CODE NUMBER, -- 메인 카테고리 코드 (외래키)
    CATEGORY_NO NUMBER, -- 서브 카테고리 코드 (외래키)
    CONSTRAINT FK_MAIN_CATEGORY_CODE FOREIGN KEY (CATEGORY_CODE) REFERENCES MAIN_CATEGORY (CATEGROY_CODE),
    CONSTRAINT FK_CATEGORY_CODE FOREIGN KEY (CATEGORY_NO) REFERENCES CATEGORY (CATEGROY_NO),
    CONSTRAINT FK_MEMBER_AUCTION FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER (MEMBER_NO)
);

-- MAIN_CATEGORY 테이블
CREATE TABLE MAIN_CATEGORY (
    CATEGORY_CODE NUMBER PRIMARY KEY, -- 카테고리 코드
    CATEGORY_NAME VARCHAR2(50), -- 카테고리 이름
    CONSTRAINT FK_CATEGORY_AUCTION FOREIGN KEY (AUCTION_NO) REFERENCES AUCTION_BOARD (AUCTION_NO)
);

-- 서브 카테고리 테이블
CREATE TABLE CATEGORY (
    CATEGORY_NO NUMBER PRIMARY KEY, -- 카테고리 번호
    CATEGORY_NAME_S VARCHAR2(50), -- 카테고리 이름
    AUCTION_NO NUMBER, -- 경매 번호 (외래키)
    CONSTRAINT FK_CATEGORY_AUCTION FOREIGN KEY (AUCTION_NO) REFERENCES AUCTION_BOARD (AUCTION_NO)
);

-- DELIVERY 배송 테이블
CREATE TABLE DELIVERY (
    DELIVERY_NO NUMBER PRIMARY KEY, -- 배송 번호
    DELIVERY_COMPANY VARCHAR2(50), -- 배송 업체
    START_DATE DATE, -- 배송 시작일
    COMPLETE_DATE DATE, -- 배송 완료일
    AUCTION_NO NUMBER, -- 경매 번호 (외래키)
    MEMBER_ID VARCHAR2(20), -- 회원 아이디 (외래키)
    CONSTRAINT FK_DELIVERY_AUCTION FOREIGN KEY (AUCTION_NO) REFERENCES AUCTION_BOARD (AUCTION_NO),
    CONSTRAINT FK_DELIVERY_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID)
);

-- INTEREST 관심 등록 테이블
CREATE TABLE INTEREST (
    INTEREST_NO NUMBER PRIMARY KEY, -- 관심 등록 번호
    MEMBER_ID VARCHAR2(20), -- 회원 아이디 (외래키)
    AUCTION_NO NUMBER, -- 경매 번호 (외래키)
    CONSTRAINT FK_INTEREST_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
    CONSTRAINT FK_INTEREST_AUCTION FOREIGN KEY (AUCTION_NO) REFERENCES AUCTION_BOARD (AUCTION_NO)
);

-- COMMENTS 댓글 테이블
CREATE TABLE COMMENTS (
    COMMENT_NO NUMBER PRIMARY KEY, -- 댓글 번호
    AUCTION_NO NUMBER REFERENCES AUCTION_BOARD (AUCTION_NO), -- 경매 번호 (외래키)
    MEMBER_ID VARCHAR2(20) REFERENCES MEMBER (MEMBER_ID), -- 회원 아이디 (외래키)
    CONTENT VARCHAR2(1000), -- 댓글 내용
    COMMENT_DATE DATE -- 댓글 작성일
);

-- REPLIES 대댓글 테이블
CREATE TABLE REPLIES (
    REPLY_ID NUMBER PRIMARY KEY, -- 대댓글 번호
    COMMENT_ID NUMBER REFERENCES COMMENTS (COMMENT_NO), -- 댓글 번호 (외래키)
    MEMBER_ID VARCHAR2(20) REFERENCES MEMBER (MEMBER_ID), -- 회원 아이디 (외래키)
    CONTENT VARCHAR2(1000), -- 대댓글 내용
    REPLY_DATE DATE -- 대댓글 작성일
);